controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    lifter_controller:
      type: joint_trajectory_controller/JointTrajectoryController



diff_drive_controller:
  ros__parameters:
    use_sim_time: true
    left_wheel_names: [base_to_left_wheel]
    right_wheel_names: [base_to_right_wheel]
    wheel_separation: 0.4
    wheel_radius: 0.1
    base_frame_id: base_link
    odom_frame_id: odom
    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    enable_odom_tf: true
    use_stamped_vel: false

lifter_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - base_to_fork_lift
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true


