controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: [base_to_left_wheel]
    right_wheel_names: [base_to_right_wheel]
    wheel_separation: 0.4
    wheel_radius: 0.1
    base_frame_id: base_link
    odom_frame_id: odom
    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    enable_odom_tf: true
    use_stamped_vel: false

arm_controller:
  ros__parameters:
    joints:
      - base_to_shoulder
      - shoulder_to_upper
      - upper_to_forearm
      - forearm_to_wrist
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    joint: gripper_to_left
    action_monitor_rate: 20.0
    goal_tolerance: 0.002
    max_effort: 5.0
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0
