class MissionState:
    IDLE = 'IDLE'
    NAV_TO_PICKUP = 'NAV_TO_PICKUP'
    DETECT_COLOR = 'DETECT_COLOR'
    LOAD_CARGO = 'LOAD_CARGO'
    NAV_TO_SORT = 'NAV_TO_SORT'
    UNLOAD_CARGO = 'UNLOAD_CARGO'
    RETURN = 'RETURN'
